add dialog buttons loading/disable/show access
Dative-GPI/foundation-shared-ui pull request #429
Opened 2024-10-10 14:19 UTC by gballigand

2024-10-10 14:28 UTC, peyronth requested changes

2024-10-10 14:28 UTC, peyronth commented on dev/storybook/src/stories/shared/Dialog.stories.ts
> +          <FSText>
Mettre FSText dans components ou utiliser FSSpan

2024-10-10 14:28 UTC, peyronth commented on dev/storybook/src/stories/shared/Dialog.stories.ts
> +        ...args
tu peux utiliser juste args et nommer tes valeurs comme les props du composant, ça permet de jouer avec dans le storybook.

2024-10-10 14:28 UTC, peyronth commented on src/shared/foundation-shared-components/components/FSClickable.vue
> +
Retour à la ligne inutile.

2024-10-10 15:03 UTC, peyronth approved these changes

2024-10-14 10:56 UTC, SchroterQuentin approved these changes

2024-10-15 06:21 UTC, merged