fix FSDialogForm validation
Dative-GPI/foundation-shared-ui pull request #491
Opened 2024-11-13 14:20 UTC by gballigand

2024-11-13 14:25 UTC, rduteil requested changes

2024-11-13 14:25 UTC, rduteil commented on src/shared/foundation-shared-components/components/FSDialogForm.vue
> +    const ResetFormValidation = () => {
une majuscule sur une fonction en JS

2024-11-13 14:25 UTC, rduteil commented on src/shared/foundation-shared-components/components/FSDialogForm.vue
> +        @update:valid="validForm = $event"
Le FSDialogFormBody emit update:validForm

2024-11-13 14:29 UTC, peyronth requested changes

2024-11-13 14:29 UTC, peyronth commented on src/shared/foundation-shared-components/components/FSDialogForm.vue
> +    const bodyRef = ref<HTMLElement | null>(null);
bodyRef est pas Html element si ? Plutot typeof FSDialogFormBody je dirais
ça évitera les as any en dessous.

2024-11-13 14:29 UTC, peyronth commented on src/shared/foundation-shared-components/components/FSDialogForm.vue
> +        (bodyRef.value as any).ResetFormValidation();
Enlever les as any (même chose en dessous).

2024-11-13 14:29 UTC, peyronth commented on src/shared/foundation-shared-components/components/FSDialogFormBody.vue
>      const formRef = ref<HTMLElement | null>(null);
Même chose que le précédent commentaire.

2024-11-13 14:29 UTC, peyronth commented on src/shared/foundation-shared-components/components/FSDialogFormBody.vue
> +        await (formRef.value as any).validate();
Même chose

2024-11-13 14:29 UTC, peyronth commented on src/shared/foundation-shared-components/components/FSDialogFormBody.vue
> +        (formRef.value as any).ResetValidation();
Même chose

2024-11-13 15:30 UTC, peyronth approved these changes

2024-11-14 22:24 UTC, SchroterQuentin approved these changes

2024-11-15 07:12 UTC, rduteil approved these changes

2024-11-15 07:12 UTC, merged