Features/mountain components
Dative-GPI/foundation-shared-ui pull request #517
Opened 2024-12-18 13:44 UTC by peyronth

2024-12-19 08:12 UTC, rduteil commented on src/shared/foundation-shared-components/components/FSProgressBar.vue
> +    gap="8px"
C'est la valeur par défaut, tu peux enlever

2024-12-19 08:13 UTC, rduteil commented on src/shared/foundation-shared-components/components/FSProgressBar.vue
> +    <FSText
T'as pas importé FSText

2024-12-19 08:20 UTC, rduteil approved these changes

2025-01-08 17:04 UTC, SchroterQuentin requested changes

2025-01-09 07:38 UTC, peyronth commented on src/shared/foundation-shared-components/components/FSInstantPicker.vue
> +            minWidth='min(300px, 90vw)'
Pourquoi? C'est juste une min qui est fixe, j'estime que si on met moins de 300px à un slider il n'est pas utilisable correctement donc je préfère qu'il wrap.

2025-01-09 07:46 UTC, peyronth commented on src/shared/foundation-shared-components/components/FSInstantPicker.vue
> +        playingInterval.value = setInterval(() => {
C'est juste si demain on veut manipuler playing en dehors du bouton, par exemple on pourrait vouloir mettre en pause si on change la value dans le slider et ducoup le watch aura de l'intérêt.

2025-01-09 14:40 UTC, peyronth commented
Branche mergée avec #526 qui me sert ici

2025-01-13 13:05 UTC, SchroterQuentin approved these changes

2025-01-13 13:06 UTC, merged